---
title: "Assignment 2"
author: "Joe Martin"
date: "1/26/2022"
output: html_document
---

```{r}
pacman::p_load(pacman,tidyverse,lubridate)

h <- read_csv('~/MSBA/Spring 2022/ECON 6760/econ-6760/data/HOUSTNSA.csv')
h$month <- lubridate::month(h$DATE)

h_sample <- h %>%
  filter(DATE >= "1960-01-01" & DATE <= "2021-12-31")
head(h_sample)


h2 <- h %>% select(-DATE,-month)
```

```{r}
h_sample$spring <- ifelse((h_sample$month == 3|h_sample$month == 4|h_sample$month == 5),1,0)
h_sample$summer <- ifelse((h_sample$month == 6|h_sample$month == 7|h_sample$month == 8),1,0)
h_sample$fall <- ifelse((h_sample$month == 9|h_sample$month == 10|h_sample$month == 11),1,0)
h_sample$winter <- ifelse((h_sample$month == 12|h_sample$month == 1|h_sample$month == 2),1,0)
```

```{r}
# Appropriately regress the housing start series on these dummy variables, using the sample period from Jan 1950 - Dec 2021

h_sample <- h_sample %>%
  select(-month)

fit1 <- lm(HOUSTNSA ~ ., h_sample) #winter comes in as NA. Because of exact colinearity?

summary(fit1)

fit1$coefficients
```
```{r}
# Question 1 Estimated Coefficients
ec <- data.frame(fit1$coefficients)
ec
```

```{r}
# Question 1 Plot

new_ts <- ts(h2, start = c(1960,1), end = c(2021,12), frequency = 12)
y <- decompose(new_ts)
```

```{r}
plot(y$x, col = "black")
lines(y$trend, cex = , col = "red")
```

```{r}
# This is for HOUSTNSA
acf(new_ts, lag.max = 24)
```

```{r}
cpia <- cpia %>%
  filter(DATE >= '1950-01-01' & DATE <= '2021-12-31') %>%
  select(-DATE)
head(cpia)

ts_cpia <- ts(tsc,start = c(1950,01), end = c(2021,12), frequency = 12)

head(ts_cpia)
head(new_ts)
tsc <- ts_cpia[1:864]

tsc
```

```{r}
plot(diff(log(ts_cpia)))

ac <- acf(ts_cpia, lag.max=12,  type = 'correlation', plot = FALSE)

head(ac)
```

```{r}
p_load(lmtest)
model <- lm(FTSE~DAX, data = EuStockMarkets)
lmtest::dwtest(model)
```

```{r}
fit2 <- lm(HOUSTNSA ~ 0, data = h_sample)
summary(fit2)
summary(fit1)
```

Using the simple test for serial correlation discussed in class, test the null hypothesis
that there is no autocorrelation in the inflation at the 12-month horizon. Report the test
statistic and whether you can reject or not reject the null hypothesis for a test size of
1%.

```{r}
twelve <- ts_cpia[853:864]

twelve_ts <- ts(twelve, start = c(2021,01), end=c(2021,12), frequency = 12)

p_load(EnvStats)
serialCorrelationTest(twelve_ts)

```